# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wAP19PPWZIAe_o2hUk5euv85ktB82Xzr

The dataset is collected from a Fashion and Beauty startup. The dataset is based on the supply chain of Makeup products. Features are listed below:
Product Type

SKU

Price

Availability

Number of products sold

Revenue generated

Customer demographics

Stock levels

Lead times

Order quantities

Shipping times

Shipping carriers

Shipping costs

Supplier name

Location

Lead time

Production volumes

Manufacturing lead time

Manufacturing costs

Inspection results

Defect rates

Transportation modes

Routes

# Code Preface
##import Libraries
"""

import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = 'plotly_white'

df = pd.read_csv('supply_chain_data.csv')
df.head()

df.describe()

"""##Product type and Price
analyzing the Supply Chain by looking at the relationship between the price of the products and the revenue generated by them:
"""

fig = px.scatter(df, x='Price',
                 y='Revenue generated',
                 color='Product type',
                 hover_data=['Number of products sold'],
                 trendline="ols")
fig.show()

"""People prefer spending more money on skincare products.

##Sales by Product Type
The company derives more revenue from skincare products, and the higher the price of skincare products, the more revenue they generate. Now let’s have a look at the sales by product type:
"""

sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()

pie_chart = px.pie(sales_data, values='Number of products sold', names='Product type',
                   title='Sales by Product Type',
                   hover_data=['Number of products sold'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)

pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()

"""So 45% of the business comes from skincare products, 29.5% from haircare, and 25.5% from cosmetics.

## Total Revenue by Shipping Carrier
"""

total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                     y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carrier',
                  xaxis_title='Shipping Carrier',
                  yaxis_title='Revenue Generated')
fig.show()

"""## Revenue generated by SKU"""

revenue_chart = px.line(df, x='SKU',
                        y='Revenue generated',
                        title='Revenue Generated by SKU')
revenue_chart.show()

"""## Stock Levels by SKU"""

stock_chart = px.line(df, x='SKU',
                      y='Stock levels',
                      title='Stock Levels by SKU')
stock_chart.show()

"""## Order Quantity by SKU"""

order_quantity_chart = px.bar(df, x='SKU',
                              y='Order quantities',
                              title='Order Quantity by SKU')
order_quantity_chart.show()

"""## Shipping Costs by Carrier"""

shipping_cost_chart = px.bar(df, x='Shipping carriers',
                             y='Shipping costs',
                             title='Shipping Costs by Carrier')
shipping_cost_chart.show()

"""In one of the above visualizations, we discovered that Carrier B helps the company in more revenue. It is also the most costly Carrier among the three

##Cost Distribution by Transportation Mode
"""

transportation_chart = px.pie(df,
                              values='Costs',
                              names='Transportation modes',
                              title='Cost Distribution by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()

"""So the company spends more on Road and Rail modes of transportation for the transportation of Goods.

## Analyzing Defect Rate

### Average Defect Rates by Product Type
"""

defect_rates_by_product = df.groupby('Product type')['Defect rates'].mean().reset_index()

fig = px.bar(defect_rates_by_product, x='Product type', y='Defect rates',
             title='Average Defect Rates by Product Type')
fig.show()

"""So the defect rate of haircare products is higher

##Defect Rates by Transportation Mode
"""

pivot_table = pd.pivot_table(df, values='Defect rates',
                             index=['Transportation modes'],
                             aggfunc='mean')

transportation_chart = px.pie(values=pivot_table["Defect rates"],
                              names=pivot_table.index,
                              title='Defect Rates by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()

"""Road transportation results in a higher defect rate, and Air transportation has the lowest defect rate.

## Summary
Supply Chain Analysis means analyzing various components of a Supply Chain to understand how to improve the effectiveness of the Supply Chain to create more value for customers.
"""